baseURL: "https://ashishmathew98.github.io" 
title: Ashish Mathew
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 2
        - name: Resume
          url: resume/
          weight: 3

params:
    description: "This website hosts Ashish Mathew's projects, resume and contact information."
    author: Ashish Mathew
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["projects","resume"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ashish Mathew
          subtitle: "I am a graduate student at Columbia University in the City of New York and have 3 years of experience as a data scientist in the financial services industry. My areas of interest include Anomaly Detection, Credit Risk and Fraud Detection."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Projects
              url: projects/
            - name: Resume
              url: resume/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:ashishmathew.k@outlook.com
        - name: GitHub
          url: https://github.com/ashishmathew98
        - name: Linkedin
          url: https://linkedin.com/in/amathew98 

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Ashish Mathew"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2